name: Run Tests
"on":
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Install OpenSSL 3.0.x
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: bun test
